version: '3.8'

services:
  web:
    build: .
    container_name: currency-converter
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
        - action: rebuild
          path: requirements.txt

networks:
  default:
    name: currency-network