[project]
name = "app"
version = "v1.0"
description = "Test task for Aiti Guru."
authors = [{name = "Eugene Kovalenko", email = "eugene.kovalenko.work@gmail.com"}]
readme = "README.md"
requires-python = ">= 3.12"
dependencies = [
  "fastapi",
  "uvicorn",
  "pydantic_settings",
]
